<a href="https://colab.research.google.com/github/sara12345689642/Redes-Neuronal/blob/main/La_Soluci%C3%B3n_Num%C3%A9rica_de_Sistemas_de_Ecuaciones_Lineales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejercicio 1 Eliminación de Gauss

In [1]:
import numpy as np

# Matriz de coeficientes
A = np.array([[2, 3, 1],
              [4, 1, 2],
              [3, 4, 2]], dtype=float)

# Vector de términos independientes
b = np.array([1, 2, 3], dtype=float)

# Resolviendo el sistema de ecuaciones usando eliminación de Gauss
sol = np.linalg.solve(A, b)

# Mostrar la solución
print("Solución del sistema:")
print(f"x = {sol[0]:.4f}, y = {sol[1]:.4f}, z = {sol[2]:.4f}")


Solución del sistema:
x = -1.0000, y = -0.0000, z = 3.0000


Ejercicio 2 Método de la matriz inversa

In [2]:
# Matriz de coeficientes
A = np.array([[1, 2, 3],
              [2, 1, 4],
              [3, 4, 1]], dtype=float)

# Vector de salida deseada
b = np.array([4, 6, 7], dtype=float)

# Calcular la matriz inversa
A_inv = np.linalg.inv(A)

# Multiplicar A_inv por el vector b
sol = np.dot(A_inv, b)

# Mostrar la solución
print("Pesos ajustados:")
print(f"w1 = {sol[0]:.4f}, w2 = {sol[1]:.4f}, w3 = {sol[2]:.4f}")


Pesos ajustados:
w1 = 1.7500, w2 = 0.3000, w3 = 0.5500


Ejercicio 3 Jacobi

In [3]:
def jacobi(A, b, x0, tol=1e-10, max_iter=1000):#se define jacobi
    n = len(b)
    x = x0 #aproximación inicial al vector de la solución
    for k in range(max_iter):
        x_new = np.zeros_like(x)#vector nuevo lleno de ceros
        for i in range(n):#iterar para cada fila de la matriz A
            s = sum(A[i][j] * x[j] for j in range(n) if i != j)#calcular los terminos que no incluyen x_i
            x_new[i] = (b[i] - s) / A[i][i]#Actualizar la estimación
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:#tolerancia para la convergencia 10^-10
            return x_new
        x = x_new
    return x

# Matriz de coeficientes
A = np.array([[10, -1, 2],
              [-1, 11, -1],
              [2, -1, 10]], dtype=float)

# Vector de errores
b = np.array([0.6, 1.5, 2.1], dtype=float)

# Aproximación inicial
x0 = np.zeros_like(b)

# Aplicar el método de Jacobi
sol = jacobi(A, b, x0)

print("Pesos ajustados usando Jacobi:")
print(sol)


Pesos ajustados usando Jacobi:
[0.03201923 0.15923077 0.21951923]


Ejercicio 4 Método Iterativo de Gauss-Seidel


In [4]:
import numpy as np

def gauss_seidel(A, b, x0, tol=1e-10, max_iter=1000):
    n = len(b)
    x = x0
    for k in range(max_iter):
        x_new = np.copy(x)
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i+1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iter

# Matriz de coeficientes
A = np.array([[10, -1, 2, 0],
              [-1, 11, -1, 3],
              [2, -1, 10, -1],
              [0, 3, -1, 8]], dtype=float)

# Vector de términos independientes
b = np.array([6, 25, -11, 15], dtype=float)

# Valor inicial de las incógnitas
x0 = np.zeros_like(b)

# Resolver el sistema usando el método de Gauss-Seidel
sol, iteraciones = gauss_seidel(A, b, x0)

# Mostrar la solución y el número de iteraciones
print("Solución del sistema:")
print(sol)
print(f"Número de iteraciones: {iteraciones}")


Solución del sistema:
[ 1.  2. -1.  1.]
Número de iteraciones: 11


Ejercicio 5 Descomposición de Cholesky aplicada a una red neuronal

In [5]:
from scipy.linalg import cholesky

# Matriz y vector
A = np.array([[6, 15, 55],
              [15, 55, 225],
              [55, 225, 979]], dtype=float)

b = np.array([76, 295, 1259], dtype=float)
# Descomposición de Cholesky
L = cholesky(A, lower=True)

# Resolver Ly = b
y = np.linalg.solve(L, b)

# Resolver L^T x = y
x = np.linalg.solve(L.T, y)

print("Pesos ajustados usando Cholesky:")
print(x)


Pesos ajustados usando Cholesky:
[1. 1. 1.]
